"""empty message

Revision ID: 1fdb6484a858
Revises: 
Create Date: 2020-07-11 18:26:01.933392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdb6484a858'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_request',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('terms', sa.Integer(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('result', sa.String(length=15), nullable=True),
    sa.Column('refused_policy', sa.String(length=15), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('approved_terms', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_request')
    # ### end Alembic commands ###
