version: "2"
services:
    app:
        build: .
        image: test/loan:0.1
        container_name: loan-app
        ports:
        - "8080:8080"
        links:
        - rabbit
        depends_on:
        - rabbit
    rabbit:
        image: rabbitmq:management
        hostname: rabbit
        container_name: broker
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        ports:
        - "5672:5672"
        - "15672:15672"
        expose:
        - 5672
    worker:
        build: .
        hostname: worker
        environment:
            - PYTHONPATH=$PYTHONPATH:/app/app
            - FLASK_ENV=development
            - FLASK_APP=app/main.py
        entrypoint: celery
        command: -A app.celery worker --loglevel=info
        user: nobody
        volumes:
            - .:/app
        links:
            - rabbit
            - app
        depends_on:
            - rabbit
            - app