version: "2"
services:
    app:
        build: .
        image: test/loan:0.1
        container_name: loan-app
        environment:
            - PYTHONPATH=$PYTHONPATH:/app/app
            - FLASK_ENV=staging
            - FLASK_APP=app/main.py
        ports:
        - "8080:8080"
        links:
        - rabbit
        - db
        depends_on:
        - rabbit
        - db
        expose:
        - 8080
    db:
        image: mysql:5.7
        container_name: loan-db

        ports:
            - "33060:3306"
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./database/db_scripts:/docker-entrypoint-initdb.d/
            - ./database/loan_db:/var/lib/mysql
    rabbit:
        image: rabbitmq:management
        hostname: rabbit
        container_name: broker
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        ports:
        - "5672:5672"
        - "15672:15672"
        expose:
        - 5672
    worker:
        build: .
        hostname: worker
        environment:
            - PYTHONPATH=$PYTHONPATH:/app/app
            - FLASK_ENV=staging
            - FLASK_APP=app/main.py
        entrypoint: celery
        command: -A app.celery worker --loglevel=info --concurrency=2 --pool eventlet
        volumes:
        - .:/app
        links:
        - rabbit
        - app
        depends_on:
        - rabbit
        - app
        expose:
        - 8080